services:
  app:
    build: .
    container_name: golf
    working_dir: /usr/src/app
    entrypoint: /bin/sh
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: ["-c", "yarn install && yarn dev"]